# Generated by Django 4.1.7 on 2023-02-19 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infraction', '0002_infraction_police'),
    ]

    operations = [
        migrations.AddField(
            model_name='infraction',
            name='comments',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='infraction',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
