# Generated by Django 4.1.7 on 2023-02-19 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infraction', '0003_infraction_comments_alter_infraction_timestamp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='infraction',
            old_name='police',
            new_name='policeman',
        ),
    ]
