# Generated by Django 4.1.7 on 2023-02-23 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policeman', '0002_policeman_identification_number_policeman_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policeman',
            name='identification_number',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
